name:                Brainard
version:             0.1.0.0
github:              "githubuser/Brainard"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Brainard#readme>

dependencies:
- base >= 4.7 && < 5
- esqueleto >= 3.5 && < 4
- persistent >= 2.13 && < 3
- servant >= 0.19 && < 1
- servant-server == 0.19
- servant-exceptions >= 0.2 && < 1
- servant-js >= 0.9 && < 1
- lens >= 5.1 && < 6
- text >= 1.2 && < 3
- time >= 1.9 && < 2
- mtl >= 2 && < 3
- unliftio-core >= 0.2
- containers >= 0.4 && < 1
- fast-logger >= 3 && < 4
- monad-logger >= 0.3 && < 1
- aeson >= 1.5 && < 3
- http-types >= 0.12 && < 1
- exceptions >= 0.10 && < 1
- persistent-sqlite >= 2.13 && < 3
- wai >= 3.2 && < 4
- warp >= 3.3 && < 4
- conduit >= 1.3
- servant-swagger >= 1 && < 2
- swagger2 >= 2.5 && < 3

library:
  source-dirs: src

executables:
  Brainard-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Brainard

tests:
  Brainard-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Brainard
    - hspec >= 2.9
    